mentatus:
  admin-id: 577342267
  url: ${SERVER_URL:http://localhost:8080}
  bot:
    name: Ментат Сирил
    token: 1188186144:AAFiQqu82QyxGljhJr7TeQ2VH_W775GnyQU

notification:
  update-rate-millis: 10000

logging:
  config: config/logback.xml
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${MONGO_LOG_LEVEL:INFO}

newsapi:
  token: abe624afba93421baf6ac05e9ac386b5

spring:
  data:
    mongodb:
      uri: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017/mentatus}