mentatus:
  admin-id: 577342267
  admin-name: "@skazhi_privet"
  url: ${SERVER_URL:http://localhost:8080}
  bot:
    name: Ментат Сирил
    token: 1188186144:AAFiQqu82QyxGljhJr7TeQ2VH_W775GnyQU

selenium:
  screen-width: 100
  screen-height: 100
  user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

notification:
  update-rate-millis: 10000

marketmaps:
  dir: ${MAPS_DIR:./target/classes/marketmaps/}

logging:
  config: config/logback.xml
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${MONGO_LOG_LEVEL:INFO}

newsapi:
  token: abe624afba93421baf6ac05e9ac386b5

spring:
  data:
    mongodb:
      uri: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017/mentatus}