mentatus:
  admin-id: 577342267
  bot:
    name: Ментат Сирил
    token: 1188186144:AAFiQqu82QyxGljhJr7TeQ2VH_W775GnyQU

notification:
  update-rate-millis: 10000

logging:
  config: config/logback.xml
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

newsapi:
  token: abe624afba93421baf6ac05e9ac386b5
